# -*- coding: utf-8 -*-
"""Nazwatul jannah as syakur(tugas5ddp)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120mY2JZfy_qLBpSvETqMwriZqb6MOft2
"""

mobil = ["Bangtan","Mobil","3200","Ungu","4"]
print(mobil)
mobil.append("100.000.000")
print(mobil)
mobil.append("Mobil")
print(mobil)
mobil.insert(2,"Alpard")
print(mobil)

pilih = int(input ("mau hitung apa? 1 untuk persegi, 2 untuk lingkaran, 3 segitiga"))

match pilih:
 case 1:
  print(int(input ("berapa sisinya?")) ** 2)
 case 2:
  print(3.14 * int(input ("berapa jari jari nya?")) **2)
 case 3:
  print(1/2 * int(input("berapa alasnya? ")) * int(input("berapa tingginya?")))
 case _:
  print("salah angka")

a = int(input())
if a % 2 == 0:print("bilangn genap")
else: print("bilangan ganjil")